### ISSUE TITLE
LastPass reports Auth0 form as "insecure"

### ISSUE THREAD

**Issue by hwine** [mozilla-iam/mozilla-iam#31]
This is 100% reproducible for me. I can not remember if I got this with the "legacy" LastPass extension or not. It has been on all the web extension versions so far.
![image](https://user-images.githubusercontent.com/132412/32963016-6c573150-cb83-11e7-89a4-97a03f2981ef.png)

This alert is displayed before the password is filled into the field.

**Comment by gdestuynder** [comment]
cc @gene1wood @m-branson

**Comment by gene1wood** [comment]
@hwine Interesting. When I try this with the webextension based add-on in 56 and when Tristan tries with the webextension add-on in 57 we can't reproduce it.

I'm running lastpass
 4.2.1.21a
Built: Thu Nov 09 2017 15:46:21 GMT-0500 (EST)

What browser, version of browser and version of add-on are you running?

**Comment by hwine** [comment]
> What browser, version of browser

Firefox 59.0a1 (2017-11-17) (64-bit) (I like my job)

> version of add-on are you running?

4.2.1.21 (no 'a')

I just retested with a clean profile and only LastPass installed, and could reproduce. I did notice it's an optional feature that defaults off. Do you have it set?

![image](https://user-images.githubusercontent.com/132412/32972846-45573c96-cba9-11e7-9f18-f20eea6d758b.png)

**Comment by gene1wood** [comment]
Aha, no, I don't have that option checked, it's just at default of disabled. When checking it I can reproduce what you're seeing.

Can you find out what Lastpass means by that option or what it checks for so we can figure out what is causing it?

My natural first assumption is that it's a bug in Lastpass as the [QA on their Firefox plugin is very poor](https://cs.cementhorizon.com/2017/10/24/six-years-of-lastpass-support-requests-what-have-i-learned/)

**Comment by hwine** [comment]
It's a webextension -- there's no difference between Chrome/Firefox anymore. In chrome:
![image](https://user-images.githubusercontent.com/132412/32975660-6b0eab6c-cbbe-11e7-80f2-2df02b14de08.png)

I was assuming y'all had access to a "pure" Auth0 box, so could determine if it's due to Mozilla mods, or "normal".

**Comment by gdestuynder** [comment]
Out of curiosity has this been figured out? Does the new login experience also behave like this? (https://social-ldap-pwless.testrp.security.allizom.org/ for ex)

**Comment by hwine** [comment]
I still get the message in general

I just tried the new login, and LastPass 4.2.3.20 autofill does not work for me at all, so I'm left clueless about the security of the form. 👎 

@gdestuynder - where should I file a bug re the new login experience?

**Comment by viorelaioia** [comment]
Hi @hwine !
Regarding the issue with LastPass not working on the new login experience, that is a known problem, @hidde is already working on it. 
Thanks!

**Comment by hidde** [comment]
Yes, that's right! I am on this. It's slightly tricky to get right as the password field is on a different ‘page’ than the username field. This works in some password managers (like 1Password), but not in LastPass. I am currently investigating how to get it to work.  

No need to file a new bug, this issue here will do, thanks for filing!

**Comment by hidde** [comment]
@hwine The New Login Experience problems should now be solved, and you should now: 

* see a LastPass icon in username and password fields
* when first logging in, get offered to save your credentials in LastPass
* have your credentials autofilled or use the manual filling functionality

Please let us if any of this does not work for you, so that I can follow up.

**Comment by hwine** [comment]
With latest nightly - 60.0a1 (2018-01-26) (64-bit) - on macOS,, I still get the "insecure form" prompt, and Last Pass doesn't put it's icons in the fields.

**Comment by hidde** [comment]
Hi @hwine! The screenshot seems to be of the old login form. We are testing the new one (“New Login Experience”) out on this site only https://moderator.mozilla.org. Login should redirect you to `auth-dev.mozilla.auth0.com`. Could you please verify if it works there for you?

I was unable to reproduce this on our new login experience using the 64-bit version of the latest Nightly on macOS. I have used the latest version of the LastPass extension, just to be sure.

**Comment by hwine** [comment]
yay slack! <= first time I've said _that_ ;)

During a chat with Hidde, we figured out why our results differed. I was going via the "google login", which leads to the old form.

Going through the "email" login (the new work flow) does not produce the "insecure form" dialog. 🎉
